### ISSUE TITLE
Suspicious score

### ISSUE THREAD

**Issue by hazcod** [agnivade/levenshtein#11]
Hi,

I was playing around with it, and I received these results:
```
kbc.be =? azuregateway-1faf54dd-daee-4d4f-8fb3-6c2c7458e30b-33abaad5af1b.vpn.chinacloudapi.cn (levenshtein score is80)
```

Idea why this has such a high score?

**Comment by agnivade** [comment]
The 2nd string has 83 characters. And a few characters match in the first string. I guess that's why it's 80.
