### ISSUE TITLE
Using Frogbot to scan this repository

### ISSUE THREAD

**Issue by eyalbe4** [agnivade/levenshtein#26]
My name is Eyal and my team at JFrog is maintaining [Frogbot](https://github.com/jfrog/frogbot), [JFrog CLI](https://github.com/jfrog/jfrog-cli) and few more open source projects used by our community. We're using this great library for JFrog CLI and wanted to thank you for creating this library.

We wanted to ask you whether you'd like us to install [Frogbot](https://github.com/jfrog/frogbot#readme) on this repository for you. We can set it up to scan pull requests for security vulnerabilities and/or scan the entire repository periodically. The service is completely free of charge and we'll be helping and guiding you through the setup. We'll also be supporting you in case you'll need any future assistance.

Please let me know if you're interested. We can also continue communicating about this offline.

Thanks,
Eyal

**Comment by agnivade** [comment]
Thanks! I think being such a low level repository, this does not have any dependencies on external libraries at all and I don't expect it to have in future. So I think it would not serve much benefit to have a vulnerability scanner. Let me know your thoughts.

**Comment by eyalbe4** [comment]
Got it @agnivade. Thanks.
