### ISSUE TITLE
Remove fuzz-fuzz.zip from source code

### ISSUE THREAD

**Issue by cyrilc-pro** [agnivade/levenshtein#27]
This package includes a file `fuzz/fuzz-fuzz.zip` which includes binaries (`sonar.exe`, `cover.exe`). These files are detected as vulnerable by security scanners as they were compiled with Go 1.14.1.
I think this is file should not be committed into Git.

**Comment by agnivade** [comment]
A PR would be most welcome :)

**Comment by cyrilc-pro** [comment]
What do you suggest? Can we just remove the zip file?

**Comment by agnivade** [comment]
Historically, Go exe files have been known to raise false vulnerabilities by [scanners](https://go.dev/doc/faq#virus).

This code was added quite a while back and now there's native fuzzing available in the Go toolchain. It would be great if you want to revamp the entire fuzzing part - remove all the old code, and redo fuzzing using the new way.

Otherwise, I don't think there's a big downside in keeping them.

**Comment by idoz-jfrog** [comment]
Is there a plan to issue a new tag that would include this improvement?

**Comment by agnivade** [comment]
Tagging a new release is trivial, but I usually prefer to wait until there's some material changes. Here, we have just added a native fuzzer but there's no change in the code. What are you looking for in the new release?

**Comment by idoz-jfrog** [comment]
Just looking for a clean non-vulnerable dependency via a formal tag instead of seemingly "random" commit-timestamp dependency.  Just think the consumers of this module would appreciate that.

**Comment by agnivade** [comment]
That's what I am trying to understand. The latest tagged release is 1.2: https://github.com/agnivade/levenshtein/releases/tag/v1.2.0. There has been no material improvements after that. What are you looking to use post v1.2 in this library?

**Comment by idoz-jfrog** [comment]
that tag 1.2 still has the vulnerable fuzz-fuzz module which has a very old embedded version of go which itself has over 80 vulnerabilities associated with it.  Hence a minor minor tag (1.21) would be appropriate now, as the work was done to remove this problematic module.

**Comment by agnivade** [comment]
Ah yes, that's what I wanted to know. Thanks. 1.2.1 is available now.
