### ISSUE TITLE
go version 1.13 causing build errors

### ISSUE THREAD

**Issue by EwanValentine** [agnivade/levenshtein#9]
Getting a build error in one of my project which has an indirect dependency on this repo, because the go version in your `go.mod` is set to go version `1.13`, but this version doesn't seem to exist yet, so I can't upgrade to match? Any advice appreciated!

**Comment by agnivade** [comment]
What version are you using ? If you are using module-mode, then it will not work below 1.11.4.

**Comment by EwanValentine** [comment]
It's in an AWS Codebuild pipeline, which only supports up to 1.11, so that'll be it! Cheers, I'll try and find another option

**Comment by agnivade** [comment]
Just use GOPATH mode if you are below 1.11.4. Use module mode otherwise.
